//! Raw FFI bindings for [`libultrahdr`](https://github.com/google/libultrahdr).
//!
//! The bindings are generated by `bindgen` from the vendored (or `ULTRAHDR_SRC_DIR`-provided)
//! `ultrahdr_api.h` during the build, which is why this crate has no hand-written items. Prefer the
//! safe [`ultrahdr`](https://docs.rs/ultrahdr) crate; use these types only for the corners it does
//! not wrap.
//!
//! Because the items are machine-generated from C headers, they are exempt from the usual Rust API
//! guidelines: the upstream doc comments use Doxygen markup (`\param[in] ...`) that rustdoc would
//! otherwise parse as intra-doc links.
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::invalid_html_tags)]
// `bindgen` output is not written with clippy in mind; keep the generated crate quiet.
#![allow(clippy::all)]
#![allow(clippy::pedantic)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
