//! Error and result types.

use crate::sys;
use std::error::Error as StdError;
use std::ffi::CStr;
use std::fmt;

/// Crate-wide result alias.
pub type Result<T> = std::result::Result<T, Error>;

/// Errors returned by the safe wrappers around libultrahdr.
///
/// The raw error code reported by the C library is available through [`Error::code`]; the
/// human-readable detail string through [`Error::detail`].
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum Error {
    /// A caller-supplied parameter was rejected (`UHDR_CODEC_INVALID_PARAM`).
    InvalidParameter(String),
    /// The codec is not in a state that allows the operation
    /// (`UHDR_CODEC_INVALID_OPERATION`) — for example probing a decoder before an image was
    /// registered, adding an effect after the codec ran, or reusing an encoder without calling
    /// [`Encoder::reset`](crate::Encoder::reset).
    InvalidOperation(String),
    /// Memory allocation failed (`UHDR_CODEC_MEM_ERROR`).
    Memory(String),
    /// The linked library was built without the requested feature
    /// (`UHDR_CODEC_UNSUPPORTED_FEATURE`), e.g. an output format that is compiled out of the
    /// linked build.
    UnsupportedFeature(String),
    /// Encode, decode or parse failure (`UHDR_CODEC_ERROR`).
    Codec(String),
    /// Failure without a more specific classification.
    Unknown(String),
}

impl Error {
    pub(crate) fn invalid_parameter(message: impl Into<String>) -> Self {
        Self::InvalidParameter(message.into())
    }

    pub(crate) fn invalid_operation(message: impl Into<String>) -> Self {
        Self::InvalidOperation(message.into())
    }

    pub(crate) fn allocation() -> Self {
        Self::Memory("allocation failed".to_owned())
    }

    /// The raw libultrahdr error code this error corresponds to.
    pub fn code(&self) -> sys::uhdr_codec_err_t {
        use sys::uhdr_codec_err_t::*;
        match self {
            Self::InvalidParameter(_) => UHDR_CODEC_INVALID_PARAM,
            Self::InvalidOperation(_) => UHDR_CODEC_INVALID_OPERATION,
            Self::Memory(_) => UHDR_CODEC_MEM_ERROR,
            Self::UnsupportedFeature(_) => UHDR_CODEC_UNSUPPORTED_FEATURE,
            Self::Codec(_) => UHDR_CODEC_ERROR,
            Self::Unknown(_) => UHDR_CODEC_UNKNOWN_ERROR,
        }
    }

    /// The detail message reported by the library (possibly generated by this crate).
    pub fn detail(&self) -> &str {
        match self {
            Self::InvalidParameter(detail)
            | Self::InvalidOperation(detail)
            | Self::Memory(detail)
            | Self::UnsupportedFeature(detail)
            | Self::Codec(detail)
            | Self::Unknown(detail) => detail,
        }
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let (kind, detail) = match self {
            Self::InvalidParameter(detail) => ("invalid parameter", detail),
            Self::InvalidOperation(detail) => ("invalid operation", detail),
            Self::Memory(detail) => ("memory error", detail),
            Self::UnsupportedFeature(detail) => ("unsupported feature", detail),
            Self::Codec(detail) => ("codec error", detail),
            Self::Unknown(detail) => ("unknown error", detail),
        };
        write!(f, "{kind}: {detail}")
    }
}

impl StdError for Error {}

/// Convert a `uhdr_error_info_t` into a [`Result`], preserving the library's detail string.
pub(crate) fn check(info: sys::uhdr_error_info_t) -> Result<()> {
    use sys::uhdr_codec_err_t::*;

    if info.error_code == UHDR_CODEC_OK {
        return Ok(());
    }

    let detail = if info.has_detail != 0 && info.detail[0] != 0 {
        // SAFETY: `detail` is a fixed-size buffer owned by the returned struct and is expected to
        // be NUL-terminated when `has_detail` is set.
        let detail = unsafe { CStr::from_ptr(info.detail.as_ptr()) }
            .to_string_lossy()
            .into_owned();
        if detail.is_empty() {
            format!("libultrahdr reported {:?}", info.error_code)
        } else {
            detail
        }
    } else {
        format!("libultrahdr reported {:?}", info.error_code)
    };

    Err(match info.error_code {
        UHDR_CODEC_INVALID_PARAM => Error::InvalidParameter(detail),
        UHDR_CODEC_INVALID_OPERATION => Error::InvalidOperation(detail),
        UHDR_CODEC_MEM_ERROR => Error::Memory(detail),
        UHDR_CODEC_UNSUPPORTED_FEATURE => Error::UnsupportedFeature(detail),
        UHDR_CODEC_ERROR => Error::Codec(detail),
        _ => Error::Unknown(detail),
    })
}
