//! Integration tests comparing pure Rust ultrahdr with C++ (ultrahdr-sys) golden data.
//!
//! Golden data was generated by a C program using the C++ libultrahdr library.
//!
//! **Decoder tests**: Same UltraHDR JPEG (C++ encoded), Rust decode vs C++ decode.
//! **Encoder tests**: Same RGB input, Rust enc→dec vs C++ enc→dec.
//! **Metadata tests**: Rust probe and metadata roundtrip.

use ultrahdr::decoder::Decoder;
use ultrahdr::encoder::Encoder;
use ultrahdr::types::*;

const MINNIE_WIDTH: u32 = 320;
const MINNIE_HEIGHT: u32 = 240;

const P010_WIDTH: u32 = 1280;
const P010_HEIGHT: u32 = 720;

/// Maximum linear luminance in the F16 HDR space (10000 / 203 nits).
const MAX_LINEAR: f64 = 49.2610837438;

/// Path to test data directory (relative to manifest dir).
fn test_data_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data")
}

// ============================================================================
// Helper functions
// ============================================================================

/// Compute PSNR between two u8 buffers with given peak value.
fn psnr_u8(a: &[u8], b: &[u8], peak: f64) -> f64 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match for PSNR");
    if a.is_empty() {
        return f64::INFINITY;
    }
    let mse: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&x, &y)| {
            let diff = x as f64 - y as f64;
            diff * diff
        })
        .sum::<f64>()
        / a.len() as f64;
    if mse == 0.0 {
        return f64::INFINITY;
    }
    10.0 * (peak * peak / mse).log10()
}

/// Compute PSNR between two f32 buffers (values in [0, peak]).
fn psnr_f32(a: &[f32], b: &[f32], peak: f64) -> f64 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match for PSNR");
    if a.is_empty() {
        return f64::INFINITY;
    }
    let mse: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&x, &y)| {
            let diff = x as f64 - y as f64;
            diff * diff
        })
        .sum::<f64>()
        / a.len() as f64;
    if mse == 0.0 {
        return f64::INFINITY;
    }
    10.0 * (peak * peak / mse).log10()
}

/// Compute PSNR between two u16 channel buffers.
fn psnr_u16(a: &[u16], b: &[u16], peak: f64) -> f64 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match for PSNR");
    if a.is_empty() {
        return f64::INFINITY;
    }
    let mse: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&x, &y)| {
            let diff = x as f64 - y as f64;
            diff * diff
        })
        .sum::<f64>()
        / a.len() as f64;
    if mse == 0.0 {
        return f64::INFINITY;
    }
    10.0 * (peak * peak / mse).log10()
}

/// Convert IEEE 754 half-precision (u16) to f32.
fn f16_to_f32(h: u16) -> f32 {
    let sign = ((h >> 15) & 1) as u32;
    let exp = ((h >> 10) & 0x1f) as u32;
    let mant = (h & 0x3ff) as u32;
    if exp == 0 {
        if mant == 0 {
            return f32::from_bits(sign << 31);
        }
        // Subnormal: value = (-1)^sign * 2^(-14) * (mant / 1024)
        let sign_f: f32 = if sign == 0 { 1.0 } else { -1.0 };
        return sign_f * (mant as f32 / 1024.0) * (2.0_f32).powi(-14);
    }
    if exp == 31 {
        if mant == 0 {
            return f32::from_bits((sign << 31) | 0x7f800000);
        } else {
            return f32::NAN;
        }
    }
    // Normal: rebias exponent from f16 bias (15) to f32 bias (127)
    let f32_exp = exp + 127 - 15;
    let f32_mant = mant << 13;
    f32::from_bits((sign << 31) | (f32_exp << 23) | f32_mant)
}

/// Convert raw F16 bytes (LE u16 per channel, RGBA) to f32 channel values.
fn f16_bytes_to_f32_channels(data: &[u8]) -> Vec<f32> {
    assert_eq!(data.len() % 2, 0);
    data.chunks_exact(2)
        .map(|c| f16_to_f32(u16::from_le_bytes([c[0], c[1]])))
        .collect()
}

/// Unpack RGBA1010102 (little-endian u32) buffer into per-channel u16 values (0..1023).
fn unpack_1010102(data: &[u8]) -> Vec<u16> {
    assert_eq!(data.len() % 4, 0);
    let num_pixels = data.len() / 4;
    let mut channels = Vec::with_capacity(num_pixels * 4);
    for chunk in data.chunks_exact(4) {
        let packed = u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        let r = (packed & 0x3ff) as u16;
        let g = ((packed >> 10) & 0x3ff) as u16;
        let b = ((packed >> 20) & 0x3ff) as u16;
        let a = ((packed >> 30) & 0x3) as u16;
        channels.push(r);
        channels.push(g);
        channels.push(b);
        channels.push(a);
    }
    channels
}

/// Decode an UltraHDR JPEG with specified format and transfer.
fn rust_decode(
    ultrahdr_jpeg: &[u8],
    fmt: PixelFormat,
    ct: ColorTransfer,
    expected_w: u32,
    expected_h: u32,
) -> Vec<u8> {
    let decoded = Decoder::new(ultrahdr_jpeg)
        .output_format(fmt)
        .output_transfer(ct)
        .max_display_boost(4.0)
        .decode()
        .expect("Rust decode failed");
    assert_eq!(decoded.width, expected_w);
    assert_eq!(decoded.height, expected_h);
    assert_eq!(decoded.format, fmt);
    decoded.data
}

/// Load the raw RGB test data (320x240, 3 bytes/pixel) and convert to RGBA8888.
fn load_minnie_rgba() -> Vec<u8> {
    let rgb = std::fs::read(test_data_dir().join("minnie-320x240.rgb"))
        .expect("failed to read minnie-320x240.rgb");
    assert_eq!(rgb.len(), (MINNIE_WIDTH * MINNIE_HEIGHT * 3) as usize);
    let mut rgba = Vec::with_capacity((MINNIE_WIDTH * MINNIE_HEIGHT * 4) as usize);
    for pixel in rgb.chunks_exact(3) {
        rgba.push(pixel[0]);
        rgba.push(pixel[1]);
        rgba.push(pixel[2]);
        rgba.push(255);
    }
    rgba
}

/// Encode minnie using the Rust encoder, returning UltraHDR JPEG bytes.
fn rust_encode_minnie() -> Vec<u8> {
    let hdr_rgba = load_minnie_rgba();
    let sdr_jpeg = std::fs::read(test_data_dir().join("minnie-320x240-rgb.jpg"))
        .expect("failed to read SDR JPEG");
    Encoder::new()
        .hdr_raw(
            &hdr_rgba,
            MINNIE_WIDTH,
            MINNIE_HEIGHT,
            PixelFormat::Rgba8888,
            ColorGamut::Bt709,
            ColorTransfer::Srgb,
        )
        .sdr_compressed(&sdr_jpeg, ColorGamut::Bt709)
        .quality(95)
        .encode()
        .expect("Rust encode failed")
}

// ============================================================================
// Decoder Tests: same UltraHDR JPEG (C++ encoded), Rust decode vs C++ decode
// ============================================================================

#[test]
fn test_dec_srgb_rgba8888() {
    let ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read UltraHDR JPEG");
    let golden = std::fs::read(test_data_dir().join("p010_decoded_srgb_rgba8888.bin"))
        .expect("failed to read golden data");
    assert_eq!(golden.len(), (P010_WIDTH * P010_HEIGHT * 4) as usize);

    let rust_data = rust_decode(
        &ultrahdr,
        PixelFormat::Rgba8888,
        ColorTransfer::Srgb,
        P010_WIDTH,
        P010_HEIGHT,
    );

    let psnr = psnr_u8(&rust_data, &golden, 255.0);
    eprintln!("DEC SRGB RGBA8888: PSNR = {psnr:.2} dB (threshold: 55 dB)");
    assert!(psnr > 55.0, "PSNR too low: {psnr:.2} dB");
}

#[test]
fn test_dec_linear_f16() {
    let ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read UltraHDR JPEG");
    let golden = std::fs::read(test_data_dir().join("p010_decoded_linear_f16.bin"))
        .expect("failed to read golden data");
    assert_eq!(golden.len(), (P010_WIDTH * P010_HEIGHT * 8) as usize);

    let rust_data = rust_decode(
        &ultrahdr,
        PixelFormat::RgbaF16,
        ColorTransfer::Linear,
        P010_WIDTH,
        P010_HEIGHT,
    );

    let golden_f32 = f16_bytes_to_f32_channels(&golden);
    let rust_f32 = f16_bytes_to_f32_channels(&rust_data);

    let psnr = psnr_f32(&rust_f32, &golden_f32, MAX_LINEAR);
    eprintln!("DEC LINEAR F16: PSNR = {psnr:.2} dB (peak={MAX_LINEAR:.2}, threshold: 50 dB)");
    assert!(psnr > 50.0, "PSNR too low: {psnr:.2} dB");
}

#[test]
fn test_dec_hlg_1010102() {
    let ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read UltraHDR JPEG");
    let golden = std::fs::read(test_data_dir().join("p010_decoded_hlg_1010102.bin"))
        .expect("failed to read golden data");
    assert_eq!(golden.len(), (P010_WIDTH * P010_HEIGHT * 4) as usize);

    let rust_data = rust_decode(
        &ultrahdr,
        PixelFormat::Rgba1010102,
        ColorTransfer::Hlg,
        P010_WIDTH,
        P010_HEIGHT,
    );

    let golden_u16 = unpack_1010102(&golden);
    let rust_u16 = unpack_1010102(&rust_data);

    let psnr = psnr_u16(&rust_u16, &golden_u16, 1023.0);
    eprintln!("DEC HLG 1010102: PSNR = {psnr:.2} dB (peak=1023, threshold: 30 dB)");
    assert!(psnr > 30.0, "PSNR too low: {psnr:.2} dB");
}

#[test]
fn test_dec_pq_1010102() {
    let ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read UltraHDR JPEG");
    let golden = std::fs::read(test_data_dir().join("p010_decoded_pq_1010102.bin"))
        .expect("failed to read golden data");
    assert_eq!(golden.len(), (P010_WIDTH * P010_HEIGHT * 4) as usize);

    let rust_data = rust_decode(
        &ultrahdr,
        PixelFormat::Rgba1010102,
        ColorTransfer::Pq,
        P010_WIDTH,
        P010_HEIGHT,
    );

    let golden_u16 = unpack_1010102(&golden);
    let rust_u16 = unpack_1010102(&rust_data);

    let psnr = psnr_u16(&rust_u16, &golden_u16, 1023.0);
    eprintln!("DEC PQ 1010102: PSNR = {psnr:.2} dB (peak=1023, threshold: 30 dB)");
    assert!(psnr > 30.0, "PSNR too low: {psnr:.2} dB");
}

// ============================================================================
// Encoder Tests: same RGB input, Rust enc→dec vs C++ enc→dec
// ============================================================================

#[test]
fn test_enc_minnie_srgb() {
    let rust_ultrahdr = rust_encode_minnie();
    let golden = std::fs::read(test_data_dir().join("minnie_sys_srgb_rgba8888.bin"))
        .expect("failed to read golden data");

    let rust_dec = rust_decode(
        &rust_ultrahdr,
        PixelFormat::Rgba8888,
        ColorTransfer::Srgb,
        MINNIE_WIDTH,
        MINNIE_HEIGHT,
    );

    let psnr = psnr_u8(&rust_dec, &golden, 255.0);
    eprintln!("ENC MINNIE SRGB: PSNR = {psnr:.2} dB (threshold: 30 dB)");
    assert!(psnr > 30.0, "PSNR too low: {psnr:.2} dB");
}

#[test]
fn test_enc_minnie_linear() {
    let rust_ultrahdr = rust_encode_minnie();
    let golden = std::fs::read(test_data_dir().join("minnie_sys_linear_f16.bin"))
        .expect("failed to read golden data");

    let rust_dec = rust_decode(
        &rust_ultrahdr,
        PixelFormat::RgbaF16,
        ColorTransfer::Linear,
        MINNIE_WIDTH,
        MINNIE_HEIGHT,
    );

    let golden_f32 = f16_bytes_to_f32_channels(&golden);
    let rust_f32 = f16_bytes_to_f32_channels(&rust_dec);

    let psnr = psnr_f32(&rust_f32, &golden_f32, MAX_LINEAR);
    eprintln!("ENC MINNIE LINEAR: PSNR = {psnr:.2} dB (peak={MAX_LINEAR:.2}, threshold: 25 dB)");
    assert!(psnr > 25.0, "PSNR too low: {psnr:.2} dB");
}

#[test]
fn test_enc_minnie_hlg() {
    let rust_ultrahdr = rust_encode_minnie();
    let golden = std::fs::read(test_data_dir().join("minnie_sys_hlg_1010102.bin"))
        .expect("failed to read golden data");

    let rust_dec = rust_decode(
        &rust_ultrahdr,
        PixelFormat::Rgba1010102,
        ColorTransfer::Hlg,
        MINNIE_WIDTH,
        MINNIE_HEIGHT,
    );

    let golden_u16 = unpack_1010102(&golden);
    let rust_u16 = unpack_1010102(&rust_dec);

    let psnr = psnr_u16(&rust_u16, &golden_u16, 1023.0);
    eprintln!("ENC MINNIE HLG: PSNR = {psnr:.2} dB (peak=1023, threshold: 20 dB)");
    assert!(psnr > 20.0, "PSNR too low: {psnr:.2} dB");
}

#[test]
fn test_enc_minnie_pq() {
    let rust_ultrahdr = rust_encode_minnie();
    let golden = std::fs::read(test_data_dir().join("minnie_sys_pq_1010102.bin"))
        .expect("failed to read golden data");

    let rust_dec = rust_decode(
        &rust_ultrahdr,
        PixelFormat::Rgba1010102,
        ColorTransfer::Pq,
        MINNIE_WIDTH,
        MINNIE_HEIGHT,
    );

    let golden_u16 = unpack_1010102(&golden);
    let rust_u16 = unpack_1010102(&rust_dec);

    let psnr = psnr_u16(&rust_u16, &golden_u16, 1023.0);
    eprintln!("ENC MINNIE PQ: PSNR = {psnr:.2} dB (peak=1023, threshold: 20 dB)");
    assert!(psnr > 20.0, "PSNR too low: {psnr:.2} dB");
}

// ============================================================================
// Metadata Tests
// ============================================================================

#[test]
fn test_probe_metadata() {
    let ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read UltraHDR JPEG");

    let metadata = Decoder::new(&ultrahdr)
        .probe()
        .expect("probe failed")
        .expect("C++ encoded JPEG should contain gain map metadata");

    eprintln!("P010 C++ metadata via Rust probe: {:?}", metadata);

    // Real HDR content should have significant content boost
    assert!(
        metadata.max_content_boost[0] > 1.0,
        "max_content_boost[0] should be > 1.0, got {}",
        metadata.max_content_boost[0]
    );
    assert!(
        metadata.hdr_capacity_max > 1.0,
        "hdr_capacity_max should be > 1.0, got {}",
        metadata.hdr_capacity_max
    );

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] should be positive, got {}",
            metadata.gamma[i]
        );
    }
}

#[test]
fn test_metadata_roundtrip() {
    let rust_ultrahdr = rust_encode_minnie();

    let metadata = Decoder::new(&rust_ultrahdr)
        .probe()
        .expect("probe failed")
        .expect("Rust encoded JPEG should contain gain map metadata");

    eprintln!("Rust enc metadata: {:?}", metadata);

    for i in 0..3 {
        assert!(
            metadata.max_content_boost[i] >= 1.0,
            "max_content_boost[{i}] = {} should be >= 1.0",
            metadata.max_content_boost[i]
        );
    }

    for i in 0..3 {
        assert!(
            metadata.min_content_boost[i] > 0.0 && metadata.min_content_boost[i] <= 1.0,
            "min_content_boost[{i}] = {} should be in (0, 1]",
            metadata.min_content_boost[i]
        );
    }

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] = {} should be positive",
            metadata.gamma[i]
        );
    }

    assert!(
        metadata.hdr_capacity_max >= metadata.hdr_capacity_min,
        "hdr_capacity_max ({}) should be >= hdr_capacity_min ({})",
        metadata.hdr_capacity_max,
        metadata.hdr_capacity_min
    );
}
