//! Integration tests comparing pure Rust ultrahdr with C++ (ultrahdr-sys) golden data.
//!
//! Golden data was generated by a C program using the C++ libultrahdr library.
//! Two test image sets:
//! - "minnie" 320x240 SDR (RGB) — tests Rust encoder round-trip and metadata
//! - "p010" 1280x720 real HDR (P010+YUV420) — tests Rust decoder vs C++ decoder

use ultrahdr::decoder::Decoder;
use ultrahdr::encoder::Encoder;
use ultrahdr::types::*;

const MINNIE_WIDTH: u32 = 320;
const MINNIE_HEIGHT: u32 = 240;

const P010_WIDTH: u32 = 1280;
const P010_HEIGHT: u32 = 720;

/// Path to test data directory (relative to manifest dir).
fn test_data_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data")
}

/// Compute PSNR between two u8 buffers.
fn psnr(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match for PSNR");
    if a.is_empty() {
        return f64::INFINITY;
    }
    let mse: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&x, &y)| {
            let diff = x as f64 - y as f64;
            diff * diff
        })
        .sum::<f64>()
        / a.len() as f64;
    if mse == 0.0 {
        return f64::INFINITY;
    }
    10.0 * (255.0_f64 * 255.0 / mse).log10()
}

/// Maximum per-pixel channel difference between two u8 buffers.
fn max_pixel_diff(a: &[u8], b: &[u8]) -> u8 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match");
    a.iter()
        .zip(b.iter())
        .map(|(&x, &y)| x.abs_diff(y))
        .max()
        .unwrap_or(0)
}

/// Load the raw RGB test data (320x240, 3 bytes/pixel) and convert to RGBA8888.
fn load_minnie_rgba() -> Vec<u8> {
    let rgb = std::fs::read(test_data_dir().join("minnie-320x240.rgb"))
        .expect("failed to read minnie-320x240.rgb");
    assert_eq!(rgb.len(), (MINNIE_WIDTH * MINNIE_HEIGHT * 3) as usize);
    let mut rgba = Vec::with_capacity((MINNIE_WIDTH * MINNIE_HEIGHT * 4) as usize);
    for pixel in rgb.chunks_exact(3) {
        rgba.push(pixel[0]);
        rgba.push(pixel[1]);
        rgba.push(pixel[2]);
        rgba.push(255);
    }
    rgba
}

/// Decode an UltraHDR JPEG using the pure Rust decoder, returning RGBA8888 SRGB pixels.
fn rust_decode_to_rgba8888(ultrahdr_jpeg: &[u8], expected_w: u32, expected_h: u32) -> Vec<u8> {
    let decoded = Decoder::new(ultrahdr_jpeg)
        .output_format(PixelFormat::Rgba8888)
        .output_transfer(ColorTransfer::Srgb)
        .max_display_boost(4.0)
        .decode()
        .expect("Rust decode failed");
    assert_eq!(decoded.width, expected_w);
    assert_eq!(decoded.height, expected_h);
    assert_eq!(decoded.format, PixelFormat::Rgba8888);
    decoded.data
}

// ============================================================================
// P010 HDR golden data tests (real 10-bit HDR content, 1280x720)
// ============================================================================

/// Test that the Rust decoder can decode a C++-encoded UltraHDR JPEG (from real
/// P010 HDR input) and produce output close to what the C++ decoder produced.
#[test]
fn test_decode_p010_sys_encoded_jpeg() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read P010 golden UltraHDR JPEG");
    let sys_decoded = std::fs::read(test_data_dir().join("p010_decoded_sys_rgba8888.bin"))
        .expect("failed to read P010 golden decoded pixels");
    assert_eq!(
        sys_decoded.len(),
        (P010_WIDTH * P010_HEIGHT * 4) as usize,
        "golden decoded pixel size mismatch"
    );

    let rust_decoded = rust_decode_to_rgba8888(&sys_ultrahdr, P010_WIDTH, P010_HEIGHT);

    let psnr_val = psnr(&rust_decoded, &sys_decoded);
    let max_diff = max_pixel_diff(&rust_decoded, &sys_decoded);

    eprintln!(
        "P010 Rust vs C++ decode: PSNR={:.2} dB, max_diff={}",
        psnr_val, max_diff
    );

    // With real HDR data (max_content_boost up to 918x), small differences in
    // SDR base pixels from different JPEG decoders (libjpeg-turbo vs jpeg-decoder)
    // get amplified by the gain map. PSNR > 20 dB confirms the images are
    // structurally similar despite implementation differences.
    assert!(
        psnr_val > 20.0,
        "PSNR between Rust and C++ decoded P010 pixels is too low: {psnr_val:.2} dB"
    );
}

/// Test that Rust decoder can probe the C++-encoded P010 UltraHDR JPEG for metadata.
#[test]
fn test_probe_p010_sys_encoded() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read P010 golden UltraHDR JPEG");

    let metadata = Decoder::new(&sys_ultrahdr)
        .probe()
        .expect("probe failed")
        .expect("C++ encoded P010 JPEG should contain gain map metadata");

    eprintln!("P010 C++ metadata via Rust probe: {:?}", metadata);

    // Real HDR content should have significant content boost
    assert!(
        metadata.max_content_boost[0] > 1.0,
        "max_content_boost[0] should be > 1.0, got {}",
        metadata.max_content_boost[0]
    );
    assert!(
        metadata.hdr_capacity_max > 1.0,
        "hdr_capacity_max should be > 1.0, got {}",
        metadata.hdr_capacity_max
    );

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] should be positive, got {}",
            metadata.gamma[i]
        );
    }
}

// ============================================================================
// Minnie SDR tests (320x240, Rust encoder round-trip and metadata)
// ============================================================================

/// Test that the Rust decoder can decode the C++-encoded minnie UltraHDR JPEG
/// and produce output close to what the C++ decoder produced.
#[test]
fn test_decode_minnie_sys_encoded_jpeg() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("minnie_ultrahdr_sys.jpg"))
        .expect("failed to read golden UltraHDR JPEG");
    let sys_decoded = std::fs::read(test_data_dir().join("minnie_decoded_sys_rgba8888.bin"))
        .expect("failed to read golden decoded pixels");
    assert_eq!(
        sys_decoded.len(),
        (MINNIE_WIDTH * MINNIE_HEIGHT * 4) as usize
    );

    let rust_decoded = rust_decode_to_rgba8888(&sys_ultrahdr, MINNIE_WIDTH, MINNIE_HEIGHT);

    let psnr_val = psnr(&rust_decoded, &sys_decoded);
    let max_diff = max_pixel_diff(&rust_decoded, &sys_decoded);

    eprintln!(
        "Minnie Rust vs C++ decode: PSNR={:.2} dB, max_diff={}",
        psnr_val, max_diff
    );

    // Minnie uses SDR data as HDR input, so PSNR is lower than real HDR.
    assert!(
        psnr_val > 10.0,
        "PSNR between Rust and C++ decoded minnie pixels is too low: {psnr_val:.2} dB"
    );
}

/// Test round-trip: Rust encoder -> Rust decoder, verify output is reasonable
/// compared to the original HDR pixels.
#[test]
fn test_roundtrip_pixel_tolerance() {
    let hdr_rgba = load_minnie_rgba();
    let sdr_jpeg = std::fs::read(test_data_dir().join("minnie-320x240-rgb.jpg"))
        .expect("failed to read SDR JPEG");

    let ultrahdr_jpeg = Encoder::new()
        .hdr_raw(
            &hdr_rgba,
            MINNIE_WIDTH,
            MINNIE_HEIGHT,
            PixelFormat::Rgba8888,
            ColorGamut::Bt709,
            ColorTransfer::Srgb,
        )
        .sdr_compressed(&sdr_jpeg, ColorGamut::Bt709)
        .quality(95)
        .encode()
        .expect("Rust encode failed");

    let decoded = rust_decode_to_rgba8888(&ultrahdr_jpeg, MINNIE_WIDTH, MINNIE_HEIGHT);

    let psnr_val = psnr(&decoded, &hdr_rgba);
    eprintln!(
        "Rust roundtrip PSNR: {:.2} dB, decoded_len={}, original_len={}",
        psnr_val,
        decoded.len(),
        hdr_rgba.len()
    );

    assert!(
        psnr_val > 20.0,
        "Round-trip PSNR is too low: {psnr_val:.2} dB"
    );
}

/// Test that Rust encoder produces valid metadata that can be probed.
#[test]
fn test_metadata_preservation() {
    let hdr_rgba = load_minnie_rgba();
    let sdr_jpeg = std::fs::read(test_data_dir().join("minnie-320x240-rgb.jpg"))
        .expect("failed to read SDR JPEG");

    let ultrahdr_jpeg = Encoder::new()
        .hdr_raw(
            &hdr_rgba,
            MINNIE_WIDTH,
            MINNIE_HEIGHT,
            PixelFormat::Rgba8888,
            ColorGamut::Bt709,
            ColorTransfer::Srgb,
        )
        .sdr_compressed(&sdr_jpeg, ColorGamut::Bt709)
        .quality(95)
        .encode()
        .expect("Rust encode failed");

    let metadata = Decoder::new(&ultrahdr_jpeg)
        .probe()
        .expect("probe failed")
        .expect("should contain gain map metadata");

    eprintln!("Rust metadata: {:?}", metadata);

    for i in 0..3 {
        assert!(
            metadata.max_content_boost[i] >= 1.0,
            "max_content_boost[{i}] = {} should be >= 1.0",
            metadata.max_content_boost[i]
        );
    }

    for i in 0..3 {
        assert!(
            metadata.min_content_boost[i] > 0.0 && metadata.min_content_boost[i] <= 1.0,
            "min_content_boost[{i}] = {} should be in (0, 1]",
            metadata.min_content_boost[i]
        );
    }

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] = {} should be positive",
            metadata.gamma[i]
        );
    }

    assert!(
        metadata.hdr_capacity_max >= metadata.hdr_capacity_min,
        "hdr_capacity_max ({}) should be >= hdr_capacity_min ({})",
        metadata.hdr_capacity_max,
        metadata.hdr_capacity_min
    );
}

/// Test that Rust decoder can probe the C++-encoded minnie UltraHDR JPEG for metadata.
#[test]
fn test_probe_minnie_sys_encoded() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("minnie_ultrahdr_sys.jpg"))
        .expect("failed to read golden UltraHDR JPEG");

    let metadata = Decoder::new(&sys_ultrahdr)
        .probe()
        .expect("probe failed")
        .expect("C++ encoded JPEG should contain gain map metadata");

    eprintln!("C++ metadata via Rust probe: {:?}", metadata);

    assert!(
        metadata.max_content_boost[0] > 1.0,
        "max_content_boost[0] should be > 1.0, got {}",
        metadata.max_content_boost[0]
    );
    assert!(
        metadata.hdr_capacity_max > 1.0,
        "hdr_capacity_max should be > 1.0, got {}",
        metadata.hdr_capacity_max
    );

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] should be positive, got {}",
            metadata.gamma[i]
        );
    }
}
