//! Integration tests comparing pure Rust ultrahdr with C++ (ultrahdr-sys) golden data.
//!
//! Golden data was generated by a C program using the C++ libultrahdr library.
//! Two test image sets:
//! - "minnie" 320x240 SDR (RGB) — tests Rust encoder round-trip and metadata
//! - "p010" 1280x720 real HDR (P010+YUV420) — tests Rust decoder vs C++ decoder

use ultrahdr::decoder::Decoder;
use ultrahdr::encoder::Encoder;
use ultrahdr::types::*;

const MINNIE_WIDTH: u32 = 320;
const MINNIE_HEIGHT: u32 = 240;

const P010_WIDTH: u32 = 1280;
const P010_HEIGHT: u32 = 720;

/// Path to test data directory (relative to manifest dir).
fn test_data_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data")
}

/// Compute PSNR between two u8 buffers.
fn psnr(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match for PSNR");
    if a.is_empty() {
        return f64::INFINITY;
    }
    let mse: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&x, &y)| {
            let diff = x as f64 - y as f64;
            diff * diff
        })
        .sum::<f64>()
        / a.len() as f64;
    if mse == 0.0 {
        return f64::INFINITY;
    }
    10.0 * (255.0_f64 * 255.0 / mse).log10()
}

/// Maximum per-pixel channel difference between two u8 buffers.
fn max_pixel_diff(a: &[u8], b: &[u8]) -> u8 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match");
    a.iter()
        .zip(b.iter())
        .map(|(&x, &y)| x.abs_diff(y))
        .max()
        .unwrap_or(0)
}

/// Load the raw RGB test data (320x240, 3 bytes/pixel) and convert to RGBA8888.
fn load_minnie_rgba() -> Vec<u8> {
    let rgb = std::fs::read(test_data_dir().join("minnie-320x240.rgb"))
        .expect("failed to read minnie-320x240.rgb");
    assert_eq!(rgb.len(), (MINNIE_WIDTH * MINNIE_HEIGHT * 3) as usize);
    let mut rgba = Vec::with_capacity((MINNIE_WIDTH * MINNIE_HEIGHT * 4) as usize);
    for pixel in rgb.chunks_exact(3) {
        rgba.push(pixel[0]);
        rgba.push(pixel[1]);
        rgba.push(pixel[2]);
        rgba.push(255);
    }
    rgba
}

/// Decode an UltraHDR JPEG using the pure Rust decoder, returning RGBA8888 SRGB pixels.
fn rust_decode_to_rgba8888(ultrahdr_jpeg: &[u8], expected_w: u32, expected_h: u32) -> Vec<u8> {
    let decoded = Decoder::new(ultrahdr_jpeg)
        .output_format(PixelFormat::Rgba8888)
        .output_transfer(ColorTransfer::Srgb)
        .max_display_boost(4.0)
        .decode()
        .expect("Rust decode failed");
    assert_eq!(decoded.width, expected_w);
    assert_eq!(decoded.height, expected_h);
    assert_eq!(decoded.format, PixelFormat::Rgba8888);
    decoded.data
}

/// Decode an UltraHDR JPEG with specified format and transfer.
fn rust_decode(
    ultrahdr_jpeg: &[u8],
    fmt: PixelFormat,
    ct: ColorTransfer,
    expected_w: u32,
    expected_h: u32,
) -> Vec<u8> {
    let decoded = Decoder::new(ultrahdr_jpeg)
        .output_format(fmt)
        .output_transfer(ct)
        .max_display_boost(4.0)
        .decode()
        .expect("Rust decode failed");
    assert_eq!(decoded.width, expected_w);
    assert_eq!(decoded.height, expected_h);
    assert_eq!(decoded.format, fmt);
    decoded.data
}

/// Convert IEEE 754 half-precision (u16) to f32.
fn f16_to_f32(h: u16) -> f32 {
    let sign = ((h >> 15) & 1) as u32;
    let exp = ((h >> 10) & 0x1f) as u32;
    let mant = (h & 0x3ff) as u32;
    if exp == 0 {
        // Subnormal or zero
        let val = f32::from_bits((sign << 31) | 0);
        if mant == 0 {
            return val;
        }
        // Subnormal: value = (-1)^sign * 2^(-14) * (mant / 1024)
        let sign_f: f32 = if sign == 0 { 1.0 } else { -1.0 };
        return sign_f * (mant as f32 / 1024.0) * (2.0_f32).powi(-14);
    }
    if exp == 31 {
        // Inf or NaN
        if mant == 0 {
            return f32::from_bits((sign << 31) | 0x7f800000);
        } else {
            return f32::NAN;
        }
    }
    // Normal: rebias exponent from f16 bias (15) to f32 bias (127)
    let f32_exp = exp + 127 - 15;
    let f32_mant = mant << 13; // 10-bit -> 23-bit
    f32::from_bits((sign << 31) | (f32_exp << 23) | f32_mant)
}

/// Compute PSNR between two f32 buffers (values in [0, peak]).
fn psnr_f32(a: &[f32], b: &[f32], peak: f64) -> f64 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match for PSNR");
    if a.is_empty() {
        return f64::INFINITY;
    }
    let mse: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&x, &y)| {
            let diff = x as f64 - y as f64;
            diff * diff
        })
        .sum::<f64>()
        / a.len() as f64;
    if mse == 0.0 {
        return f64::INFINITY;
    }
    10.0 * (peak * peak / mse).log10()
}

/// Unpack RGBA1010102 (little-endian u32) buffer into per-channel u16 values (0..1023).
fn unpack_1010102(data: &[u8]) -> Vec<u16> {
    assert_eq!(data.len() % 4, 0);
    let num_pixels = data.len() / 4;
    let mut channels = Vec::with_capacity(num_pixels * 4);
    for chunk in data.chunks_exact(4) {
        let packed = u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        let r = (packed & 0x3ff) as u16;
        let g = ((packed >> 10) & 0x3ff) as u16;
        let b = ((packed >> 20) & 0x3ff) as u16;
        let a = ((packed >> 30) & 0x3) as u16;
        channels.push(r);
        channels.push(g);
        channels.push(b);
        channels.push(a);
    }
    channels
}

/// Compute PSNR between two u16 channel buffers (10-bit, peak=1023).
fn psnr_u16(a: &[u16], b: &[u16], peak: f64) -> f64 {
    assert_eq!(a.len(), b.len(), "buffer lengths must match for PSNR");
    if a.is_empty() {
        return f64::INFINITY;
    }
    let mse: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&x, &y)| {
            let diff = x as f64 - y as f64;
            diff * diff
        })
        .sum::<f64>()
        / a.len() as f64;
    if mse == 0.0 {
        return f64::INFINITY;
    }
    10.0 * (peak * peak / mse).log10()
}

/// Convert raw F16 bytes (LE u16 per channel, RGBA) to f32 channel values.
fn f16_bytes_to_f32_channels(data: &[u8]) -> Vec<f32> {
    assert_eq!(data.len() % 2, 0);
    data.chunks_exact(2)
        .map(|c| f16_to_f32(u16::from_le_bytes([c[0], c[1]])))
        .collect()
}

// ============================================================================
// P010 HDR golden data tests (real 10-bit HDR content, 1280x720)
// ============================================================================

/// Measure PSNR of both Rust and C++ decoded outputs against a quality-100
/// reference (minimal JPEG compression loss). This shows encode-decode
/// pipeline quality for each implementation.
#[test]
fn test_psnr_vs_reference() {
    let reference = std::fs::read(test_data_dir().join("p010_reference_rgba8888.bin"))
        .expect("failed to read reference pixels");
    let sys_decoded = std::fs::read(test_data_dir().join("p010_decoded_sys_rgba8888.bin"))
        .expect("failed to read C++ decoded pixels");
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read UltraHDR JPEG");
    let rust_decoded = rust_decode_to_rgba8888(&sys_ultrahdr, P010_WIDTH, P010_HEIGHT);

    let cpp_psnr = psnr(&sys_decoded, &reference);
    let rust_psnr = psnr(&rust_decoded, &reference);
    let cpp_vs_rust = psnr(&sys_decoded, &rust_decoded);

    eprintln!("=== PSNR vs q100 reference (P010 1280x720) ===");
    eprintln!("  C++ decoded vs reference:  {cpp_psnr:.2} dB");
    eprintln!("  Rust decoded vs reference: {rust_psnr:.2} dB");
    eprintln!("  C++ vs Rust decoded:       {cpp_vs_rust:.2} dB");
}

/// Test that the Rust decoder can decode a C++-encoded UltraHDR JPEG (from real
/// P010 HDR input) and produce output close to what the C++ decoder produced.
#[test]
fn test_decode_p010_sys_encoded_jpeg() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read P010 golden UltraHDR JPEG");
    let sys_decoded = std::fs::read(test_data_dir().join("p010_decoded_sys_rgba8888.bin"))
        .expect("failed to read P010 golden decoded pixels");
    assert_eq!(
        sys_decoded.len(),
        (P010_WIDTH * P010_HEIGHT * 4) as usize,
        "golden decoded pixel size mismatch"
    );

    let rust_decoded = rust_decode_to_rgba8888(&sys_ultrahdr, P010_WIDTH, P010_HEIGHT);

    let psnr_val = psnr(&rust_decoded, &sys_decoded);
    let max_diff = max_pixel_diff(&rust_decoded, &sys_decoded);

    eprintln!(
        "P010 Rust vs C++ decode: PSNR={:.2} dB, max_diff={}",
        psnr_val, max_diff
    );

    // With real HDR data (max_content_boost up to 918x), small differences in
    // SDR base pixels from different JPEG decoders (libjpeg-turbo vs jpeg-decoder)
    // get amplified by the gain map. PSNR > 20 dB confirms the images are
    // structurally similar despite implementation differences.
    assert!(
        psnr_val > 20.0,
        "PSNR between Rust and C++ decoded P010 pixels is too low: {psnr_val:.2} dB"
    );
}

/// Test that Rust decoder can probe the C++-encoded P010 UltraHDR JPEG for metadata.
#[test]
fn test_probe_p010_sys_encoded() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read P010 golden UltraHDR JPEG");

    let metadata = Decoder::new(&sys_ultrahdr)
        .probe()
        .expect("probe failed")
        .expect("C++ encoded P010 JPEG should contain gain map metadata");

    eprintln!("P010 C++ metadata via Rust probe: {:?}", metadata);

    // Real HDR content should have significant content boost
    assert!(
        metadata.max_content_boost[0] > 1.0,
        "max_content_boost[0] should be > 1.0, got {}",
        metadata.max_content_boost[0]
    );
    assert!(
        metadata.hdr_capacity_max > 1.0,
        "hdr_capacity_max should be > 1.0, got {}",
        metadata.hdr_capacity_max
    );

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] should be positive, got {}",
            metadata.gamma[i]
        );
    }
}

// ============================================================================
// Minnie SDR tests (320x240, Rust encoder round-trip and metadata)
// ============================================================================

/// Test that the Rust decoder can decode the C++-encoded minnie UltraHDR JPEG
/// and produce output close to what the C++ decoder produced.
#[test]
fn test_decode_minnie_sys_encoded_jpeg() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("minnie_ultrahdr_sys.jpg"))
        .expect("failed to read golden UltraHDR JPEG");
    let sys_decoded = std::fs::read(test_data_dir().join("minnie_decoded_sys_rgba8888.bin"))
        .expect("failed to read golden decoded pixels");
    assert_eq!(
        sys_decoded.len(),
        (MINNIE_WIDTH * MINNIE_HEIGHT * 4) as usize
    );

    let rust_decoded = rust_decode_to_rgba8888(&sys_ultrahdr, MINNIE_WIDTH, MINNIE_HEIGHT);

    let psnr_val = psnr(&rust_decoded, &sys_decoded);
    let max_diff = max_pixel_diff(&rust_decoded, &sys_decoded);

    eprintln!(
        "Minnie Rust vs C++ decode: PSNR={:.2} dB, max_diff={}",
        psnr_val, max_diff
    );

    // Minnie uses SDR data as HDR input, so PSNR is lower than real HDR.
    assert!(
        psnr_val > 10.0,
        "PSNR between Rust and C++ decoded minnie pixels is too low: {psnr_val:.2} dB"
    );
}

/// Test round-trip: Rust encoder -> Rust decoder, verify output is reasonable
/// compared to the original HDR pixels.
#[test]
fn test_roundtrip_pixel_tolerance() {
    let hdr_rgba = load_minnie_rgba();
    let sdr_jpeg = std::fs::read(test_data_dir().join("minnie-320x240-rgb.jpg"))
        .expect("failed to read SDR JPEG");

    let ultrahdr_jpeg = Encoder::new()
        .hdr_raw(
            &hdr_rgba,
            MINNIE_WIDTH,
            MINNIE_HEIGHT,
            PixelFormat::Rgba8888,
            ColorGamut::Bt709,
            ColorTransfer::Srgb,
        )
        .sdr_compressed(&sdr_jpeg, ColorGamut::Bt709)
        .quality(95)
        .encode()
        .expect("Rust encode failed");

    let decoded = rust_decode_to_rgba8888(&ultrahdr_jpeg, MINNIE_WIDTH, MINNIE_HEIGHT);

    let psnr_val = psnr(&decoded, &hdr_rgba);
    eprintln!(
        "Rust roundtrip PSNR: {:.2} dB, decoded_len={}, original_len={}",
        psnr_val,
        decoded.len(),
        hdr_rgba.len()
    );

    assert!(
        psnr_val > 20.0,
        "Round-trip PSNR is too low: {psnr_val:.2} dB"
    );
}

/// Test that Rust encoder produces valid metadata that can be probed.
#[test]
fn test_metadata_preservation() {
    let hdr_rgba = load_minnie_rgba();
    let sdr_jpeg = std::fs::read(test_data_dir().join("minnie-320x240-rgb.jpg"))
        .expect("failed to read SDR JPEG");

    let ultrahdr_jpeg = Encoder::new()
        .hdr_raw(
            &hdr_rgba,
            MINNIE_WIDTH,
            MINNIE_HEIGHT,
            PixelFormat::Rgba8888,
            ColorGamut::Bt709,
            ColorTransfer::Srgb,
        )
        .sdr_compressed(&sdr_jpeg, ColorGamut::Bt709)
        .quality(95)
        .encode()
        .expect("Rust encode failed");

    let metadata = Decoder::new(&ultrahdr_jpeg)
        .probe()
        .expect("probe failed")
        .expect("should contain gain map metadata");

    eprintln!("Rust metadata: {:?}", metadata);

    for i in 0..3 {
        assert!(
            metadata.max_content_boost[i] >= 1.0,
            "max_content_boost[{i}] = {} should be >= 1.0",
            metadata.max_content_boost[i]
        );
    }

    for i in 0..3 {
        assert!(
            metadata.min_content_boost[i] > 0.0 && metadata.min_content_boost[i] <= 1.0,
            "min_content_boost[{i}] = {} should be in (0, 1]",
            metadata.min_content_boost[i]
        );
    }

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] = {} should be positive",
            metadata.gamma[i]
        );
    }

    assert!(
        metadata.hdr_capacity_max >= metadata.hdr_capacity_min,
        "hdr_capacity_max ({}) should be >= hdr_capacity_min ({})",
        metadata.hdr_capacity_max,
        metadata.hdr_capacity_min
    );
}

/// Test that Rust decoder can probe the C++-encoded minnie UltraHDR JPEG for metadata.
#[test]
fn test_probe_minnie_sys_encoded() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("minnie_ultrahdr_sys.jpg"))
        .expect("failed to read golden UltraHDR JPEG");

    let metadata = Decoder::new(&sys_ultrahdr)
        .probe()
        .expect("probe failed")
        .expect("C++ encoded JPEG should contain gain map metadata");

    eprintln!("C++ metadata via Rust probe: {:?}", metadata);

    assert!(
        metadata.max_content_boost[0] > 1.0,
        "max_content_boost[0] should be > 1.0, got {}",
        metadata.max_content_boost[0]
    );
    assert!(
        metadata.hdr_capacity_max > 1.0,
        "hdr_capacity_max should be > 1.0, got {}",
        metadata.hdr_capacity_max
    );

    for i in 0..3 {
        assert!(
            metadata.gamma[i] > 0.0,
            "gamma[{i}] should be positive, got {}",
            metadata.gamma[i]
        );
    }
}

// ============================================================================
// P010 HDR multi-format decode tests (LINEAR/HLG/PQ vs C++ golden data)
// ============================================================================

/// Test Rust LINEAR + RgbaF16 decode vs C++ golden data.
/// F16 channels are converted to f32 for PSNR comparison.
#[test]
fn test_decode_p010_linear_f16() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read P010 golden UltraHDR JPEG");
    let golden = std::fs::read(test_data_dir().join("p010_decoded_linear_f16.bin"))
        .expect("failed to read LINEAR F16 golden data");
    assert_eq!(
        golden.len(),
        (P010_WIDTH * P010_HEIGHT * 8) as usize,
        "LINEAR F16 golden size mismatch"
    );

    let rust_data =
        rust_decode(&sys_ultrahdr, PixelFormat::RgbaF16, ColorTransfer::Linear, P010_WIDTH, P010_HEIGHT);
    assert_eq!(rust_data.len(), golden.len());

    let golden_f32 = f16_bytes_to_f32_channels(&golden);
    let rust_f32 = f16_bytes_to_f32_channels(&rust_data);

    // Use peak=1.0 for linear light values (HDR can exceed 1.0 but most
    // energy is in [0,1] range; using 1.0 as peak is standard for linear).
    let psnr_val = psnr_f32(&rust_f32, &golden_f32, 1.0);
    eprintln!(
        "P010 LINEAR F16 Rust vs C++: PSNR={:.2} dB (peak=1.0)",
        psnr_val
    );

    // With real HDR data (max_content_boost up to 918x), small differences in
    // SDR base pixels from different JPEG decoders get amplified by the gain map.
    // The non-linear transfer functions further distort PSNR measurement.
    // PSNR > 10 dB confirms structural similarity despite implementation differences.
    assert!(
        psnr_val > 10.0,
        "LINEAR F16 PSNR too low: {psnr_val:.2} dB"
    );
}

/// Test Rust HLG + Rgba1010102 decode vs C++ golden data.
#[test]
fn test_decode_p010_hlg_1010102() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read P010 golden UltraHDR JPEG");
    let golden = std::fs::read(test_data_dir().join("p010_decoded_hlg_1010102.bin"))
        .expect("failed to read HLG 1010102 golden data");
    assert_eq!(
        golden.len(),
        (P010_WIDTH * P010_HEIGHT * 4) as usize,
        "HLG 1010102 golden size mismatch"
    );

    let rust_data = rust_decode(
        &sys_ultrahdr,
        PixelFormat::Rgba1010102,
        ColorTransfer::Hlg,
        P010_WIDTH,
        P010_HEIGHT,
    );
    assert_eq!(rust_data.len(), golden.len());

    let golden_u16 = unpack_1010102(&golden);
    let rust_u16 = unpack_1010102(&rust_data);

    // 10-bit channels: peak = 1023
    let psnr_val = psnr_u16(&rust_u16, &golden_u16, 1023.0);
    eprintln!(
        "P010 HLG 1010102 Rust vs C++: PSNR={:.2} dB (peak=1023)",
        psnr_val
    );

    // With real HDR data (max_content_boost up to 918x), small differences in
    // SDR base pixels from different JPEG decoders get amplified by the gain map.
    // PSNR > 10 dB confirms structural similarity despite implementation differences.
    assert!(
        psnr_val > 10.0,
        "HLG 1010102 PSNR too low: {psnr_val:.2} dB"
    );
}

/// Test Rust PQ + Rgba1010102 decode vs C++ golden data.
#[test]
fn test_decode_p010_pq_1010102() {
    let sys_ultrahdr = std::fs::read(test_data_dir().join("p010_ultrahdr_sys.jpg"))
        .expect("failed to read P010 golden UltraHDR JPEG");
    let golden = std::fs::read(test_data_dir().join("p010_decoded_pq_1010102.bin"))
        .expect("failed to read PQ 1010102 golden data");
    assert_eq!(
        golden.len(),
        (P010_WIDTH * P010_HEIGHT * 4) as usize,
        "PQ 1010102 golden size mismatch"
    );

    let rust_data = rust_decode(
        &sys_ultrahdr,
        PixelFormat::Rgba1010102,
        ColorTransfer::Pq,
        P010_WIDTH,
        P010_HEIGHT,
    );
    assert_eq!(rust_data.len(), golden.len());

    let golden_u16 = unpack_1010102(&golden);
    let rust_u16 = unpack_1010102(&rust_data);

    // 10-bit channels: peak = 1023
    let psnr_val = psnr_u16(&rust_u16, &golden_u16, 1023.0);
    eprintln!(
        "P010 PQ 1010102 Rust vs C++: PSNR={:.2} dB (peak=1023)",
        psnr_val
    );

    // PQ's steep non-linear curve amplifies small linear differences significantly.
    // With extreme gain map boosts (918x), PSNR in PQ space is expected to be lower.
    // PSNR > 10 dB confirms structural similarity despite implementation differences.
    assert!(
        psnr_val > 10.0,
        "PQ 1010102 PSNR too low: {psnr_val:.2} dB"
    );
}
